### ISSUE TITLE
Why not iOS 6? Does it fail?

### ISSUE THREAD

**Issue by amcastror** [s3lvin/DXCustomCallout-ObjC#1]
Thanks

**Comment by s3lvin** [comment]
Hi!

The only reason for why I have not given iOS 6.0 pod support is that I do not have iOS 6 simulator or device with me. But if you need run it on iOS 6 then feel free to do so by adding sources to your project directly. 

I am planning to introduce some animations in the future using `UIDynamics` that may not work with iOS 6. 

Thanks for using `DXCustomCallout`!

**Comment by amcastror** [comment]
Ok, thanks

On Thursday, April 30, 2015, s3lvin notifications@github.com wrote:

> Closed #1 https://github.com/s3lvin/DXCustomCallout-ObjC/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/s3lvin/DXCustomCallout-ObjC/issues/1#event-293865784.

## 

Saludos,
Matías Castro
Dsarhoya
