### ISSUE TITLE
Problems with callout size

### ISSUE THREAD

**Issue by MaxFrax** [s3lvin/DXCustomCallout-ObjC#2]
My callout view becomes higher than it should be. After some debugging I found were this happens but I don't know why. I attach my settings too.
![schermata 2015-08-11 alle 18 55 43](https://cloud.githubusercontent.com/assets/3145452/9203977/a4acccd8-405a-11e5-87da-b8ff0a32b173.png)

![schermata 2015-08-11 alle 18 54 22](https://cloud.githubusercontent.com/assets/3145452/9203942/6e2c5de0-405a-11e5-9ba7-f624350db2a2.png)

**Comment by s3lvin** [comment]
To fix this problem please follow the following steps.
1. Disable Autolayout for your custom callout view for a moment
2. Remove the FexibleWidth and Flexible height AutoResizingMasks from your custom callout view
3. Re enable Autolayout if needed

![step1](https://cloud.githubusercontent.com/assets/6522274/9212655/824323b0-40a8-11e5-9004-a95cb0f8b6f8.jpg)
![step2](https://cloud.githubusercontent.com/assets/6522274/9212656/82434c64-40a8-11e5-9276-b63e8515bc80.jpg)

Thanks for using DXCustomCallout.

**Comment by MaxFrax** [comment]
Thank you a lot. You saved me

**Comment by s3lvin** [comment]
You are very welcome!
